Fix a JET error regarding the existence of the local variable `reducer` at a certain point (#169)
This is a forward-port of https://github.com/JuliaLang/Distributed.jl/pull/169 (https://github.com/JuliaLang/Distributed.jl/commit/1bc91f97a75c1ac321ed28dfca072cbabfad7b4c).

```
┌ var"@distributed"(__source__::LineNumberNode, __module__::Module, args::Vararg{Any}) @ Distributed /workpath/Distributed.jl/src/macros.jl:363
│ local variable `reducer` may be undefined: reducer::Any
└────────────────────
```

(cherry picked from commit 1bc91f97a75c1ac321ed28dfca072cbabfad7b4c)